title = "Bibanon Packer"
summary = "Bibanon packer is nice things"
source = "reddit"
type = "story"
tags = ["shiba", "shibe"]
stats = ["bork", "worf", "hewwo frennoz", "much wow", "amaze", "doge best"]
